### ISSUE TITLE
Received docker images are damaged

### ISSUE THREAD

**Issue by hedmanw** [dccp/docker-transfer#1]
a) The transferred images are 4.76% larger than the sent images. What's up with that?
b) $ sudo docker run lolubuntu echo "hello"
does not work, at all. Error response from daemon and what not.

I used zep1 to send various images to zep2.

**Comment by lindskogen** [comment]
From http://tuhrig.de/difference-between-save-and-export-in-docker/:

> **So what’s the difference between both?** Well, as we saw the exported version is slightly smaller. That is because it is flattened, which means it lost its history and meta-data.

**Comment by hedmanw** [comment]
Fixed in 3c2d2ab25f98a002f8a96eab667b5401c05ee7ba
ez.
